version: '3'

services:
  webapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: asp-web
    network_mode: "host"
    ports:
      - "7000:7000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
